In [1]:
! cd ~

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
! pwd

/content


In [4]:
! ls -l /content/drive/MyDrive/as/biotec/kaggle/scp/input

total 4374279
-rw------- 1 root root   37227289 Sep 12 18:36 adata_obs_meta.csv
-rw------- 1 root root 1761529901 Sep 12 18:37 adata_train.parquet
-rw------- 1 root root   92135550 Sep 12 18:39 de_train.parquet
-rw------- 1 root root       6723 Sep 12 18:39 id_map.csv
-rw------- 1 root root     943757 Sep 12 18:39 multiome_obs_meta.csv
-rw------- 1 root root 2555628667 Sep 12 18:39 multiome_train.parquet
-rw------- 1 root root   13075170 Sep 12 18:42 multiome_var_meta.csv
-rw------- 1 root root   18711844 Sep 12 18:42 sample_submission.csv


In [5]:
!pip install tensorflow

In [6]:
import numpy as np
import pandas as pd

In [7]:
train_path = '/content/drive/MyDrive/as/biotec/kaggle/scp/input'
df_train = pd.read_parquet(f"{train_path}/de_train.parquet")
print(df_train.shape)
df_train

(614, 18216)


cell_type             sm_name sm_lincs_id  \
0              NK cells        Clotrimazole    LSM-5341   
1          T cells CD4+        Clotrimazole    LSM-5341   
2          T cells CD8+        Clotrimazole    LSM-5341   
3    T regulatory cells        Clotrimazole    LSM-5341   
4              NK cells  Mometasone Furoate    LSM-3349   
..                  ...                 ...         ...   
609  T regulatory cells        Atorvastatin    LSM-5771   
610            NK cells           Riociguat   LSM-45758   
611        T cells CD4+           Riociguat   LSM-45758   
612        T cells CD8+           Riociguat   LSM-45758   
613  T regulatory cells           Riociguat   LSM-45758   

                                                SMILES  control      A1BG  \
0               Clc1ccccc1C(c1ccccc1)(c1ccccc1)n1ccnc1    False  0.104720   
1               Clc1ccccc1C(c1ccccc1)(c1ccccc1)n1ccnc1    False  0.915953   
2               Clc1ccccc1C(c1ccccc1)(c1ccccc1)n1ccnc1    False -0.387721   
3               Clc1ccccc1C(c1ccccc1)(c1ccccc1)n1ccnc1    False  0.232893   
4    C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...    False  4.290652   
..                                                 ...      ...       ...   
609  CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F...    False -0.014372   
610  COC(=O)N(C)c1c(N)nc(-c2nn(Cc3ccccc3F)c3ncccc23...    False -0.455549   
611  COC(=O)N(C)c1c(N)nc(-c2nn(Cc3ccccc3F)c3ncccc23...    False  0.338168   
612  COC(=O)N(C)c1c(N)nc(-c2nn(Cc3ccccc3F)c3ncccc23...    False  0.101138   
613  COC(=O)N(C)c1c(N)nc(-c2nn(Cc3ccccc3F)c3ncccc23...    False -0.757116   

     A1BG-AS1       A2M   A2M-AS1     A2MP1  ...      ZUP1      ZW10  \
0   -0.077524 -1.625596 -0.144545  0.143555  ... -0.227781 -0.010752   
1   -0.884380  0.371834 -0.081677 -0.498266  ... -0.494985 -0.303419   
2   -0.305378  0.567777  0.303895 -0.022653  ... -0.119422 -0.033608   
3    0.129029  0.336897  0.486946  0.767661  ...  0.451679  0.704643   
4   -0.063864 -0.017443 -0.541154  0.570982  ...  0.758474  0.510762   
..        ...       ...       ...       ...  ...       ...       ...   
609 -0.122464 -0.456366 -0.147894 -0.545382  ... -0.549987 -2.200925   
610  0.188181  0.595734 -0.100299  0.786192  ... -1.236905  0.003854   
611 -0.109079  0.270182 -0.436586 -0.069476  ...  0.077579 -1.101637   
612 -0.409724 -0.606292 -0.071300 -0.001789  ...  0.005951 -0.893093   
613  0.085910 -0.730025 -1.367801 -0.695944  ...  0.232343 -2.247816   

       ZWILCH     ZWINT      ZXDA      ZXDB      ZXDC    ZYG11B       ZYX  \
0   -0.023881  0.674536 -0.453068  0.005164 -0.094959  0.034127  0.221377   
1    0.304955 -0.333905 -0.315516 -0.369626 -0.095079  0.704780  1.096702   
2   -0.153123  0.183597 -0.555678 -1.494789 -0.213550  0.415768  0.078439   
3    0.015468 -0.103868  0.865027  0.189114  0.224700 -0.048233  0.216139   
4    0.607401 -0.123059  0.214366  0.487838 -0.819775  0.112365 -0.122193   
..        ...       ...       ...       ...       ...       ...       ...   
609  0.359806  1.073983  0.356939 -0.029603 -0.528817  0.105138  0.491015   
610 -0.197569 -0.175307  0.101391  1.028394  0.034144 -0.231642  1.023994   
611  0.457201  0.535184 -0.198404 -0.005004  0.552810 -0.209077  0.389751   
612 -1.003029 -0.080367 -0.076604  0.024849  0.012862 -0.029684  0.005506   
613 -0.346036 -0.919567 -1.131372 -0.120252 -0.064537 -0.603280 -0.098041   

        ZZEF1  
0    0.368755  
1   -0.869887  
2   -0.259365  
3   -0.085024  
4    0.676629  
..        ...  
609 -0.979951  
610 -0.064760  
611 -0.337082  
612 -1.733112  
613 -0.750681  

[614 rows x 18216 columns]

In [8]:
# %pip install rdkit

In [9]:
df_train.shape

(614, 18216)

In [10]:
submission_df = pd.read_csv(f"{train_path}/sample_submission.csv")
submission_df.head()

id  A1BG  A1BG-AS1  A2M  A2M-AS1  A2MP1  A4GALT  AAAS  AACS  AAGAB  ...  \
0   0   0.0       0.0  0.0      0.0    0.0     0.0   0.0   0.0    0.0  ...   
1   1   0.0       0.0  0.0      0.0    0.0     0.0   0.0   0.0    0.0  ...   
2   2   0.0       0.0  0.0      0.0    0.0     0.0   0.0   0.0    0.0  ...   
3   3   0.0       0.0  0.0      0.0    0.0     0.0   0.0   0.0    0.0  ...   
4   4   0.0       0.0  0.0      0.0    0.0     0.0   0.0   0.0    0.0  ...   

   ZUP1  ZW10  ZWILCH  ZWINT  ZXDA  ZXDB  ZXDC  ZYG11B  ZYX  ZZEF1  
0   0.0   0.0     0.0    0.0   0.0   0.0   0.0     0.0  0.0    0.0  
1   0.0   0.0     0.0    0.0   0.0   0.0   0.0     0.0  0.0    0.0  
2   0.0   0.0     0.0    0.0   0.0   0.0   0.0     0.0  0.0    0.0  
3   0.0   0.0     0.0    0.0   0.0   0.0   0.0     0.0  0.0    0.0  
4   0.0   0.0     0.0    0.0   0.0   0.0   0.0     0.0  0.0    0.0  

[5 rows x 18212 columns]

In [11]:
print(df_train.shape)
df_train = df_train.dropna()
print(df_train.shape)

(614, 18216)
(614, 18216)


In [12]:
# Input
# - cell_type: categorical (5)
# - sm_name: categorical (144)
# - gene_name: categorical (18,000)
# - controol: boolean
# Output
# - differential gene expression: real number
#
# Representation:
# - We need to encode some of the inputs with dense vectors, given the cardinality
#   of the gene_name input, we can't use sparse one-hot vectors (aka dummy variables)
#   because it would take too much memory.
#
# Model architecture
# The simplest way to encode the inputs is with a trainable embedding layer.
# The output is a real number (the model is a regressor) so the simplest possible model
# has a single-unit output layer with linear activation.


In [13]:
# sparse encoding
def encode(idx, size):
  x = [0] * size
  x[idx] = 1
  return x

encode(4, 6)

[0, 0, 0, 0, 1, 0]

In [14]:
# indexing
create_index = lambda names: {name:idx for idx, name in enumerate(sorted(set(names)))}

def get_indexing(names, index):
  index = [index[name] for name in names]
  return index

create_index(df_train['cell_type'].values)

{'B cells': 0,
 'Myeloid cells': 1,
 'NK cells': 2,
 'T cells CD4+': 3,
 'T cells CD8+': 4,
 'T regulatory cells': 5}

In [15]:
# create indexing tables
gene_names = list(df_train.columns[5:])
indices = {
    'cell_type': create_index(df_train['cell_type'].values),
    'sm_name': create_index(df_train['sm_name'].values),
    'gene_name': create_index(gene_names),
}
list(indices['gene_name'].items())[:10]

[('A1BG', 0),
 ('A1BG-AS1', 1),
 ('A2M', 2),
 ('A2M-AS1', 3),
 ('A2MP1', 4),
 ('A4GALT', 5),
 ('AAAS', 6),
 ('AACS', 7),
 ('AAGAB', 8),
 ('AAK1', 9)]

In [16]:
# populate the feature matrix and label array
feature_matrix_X = []
label_Y = []

# convert from dataframe to lists
cell_types = df_train['cell_type'].values
sm_names = df_train['sm_name'].values
controls = df_train['control'].values
ge_data = df_train[gene_names].values

# cell-sm combination
for cell_type, sm_name, control, gene_expressions in zip(cell_types, sm_names, controls, ge_data):
  # if not control:
  #   continue
  # print(cell_type, sm_name, control)
  # indexing of row values
  cell_type_id = indices['cell_type'][cell_type]
  sm_name_id = indices['sm_name'][sm_name]
  control_id = int(control)

  # ge columns
  for gene_name, gene_expression in zip(gene_names, gene_expressions):
    # print(gene_name, gene_expression)
    gene_name_id = indices['gene_name'][gene_name]
    feature_matrix_X.append((cell_type_id, sm_name_id, control_id, gene_name_id))
    label_Y.append(gene_expression)
  #   break
  # break

feature_matrix_X = np.array(feature_matrix_X, dtype='int32').reshape(-1,4)
label_Y = np.array(label_Y, dtype='int32').reshape(-1,1)

print(feature_matrix_X.shape, label_Y.shape)
print(feature_matrix_X[:5])
print(label_Y[:5])

(11181554, 4) (11181554, 1)
[[ 2 39  0  0]
 [ 2 39  0  1]
 [ 2 39  0  2]
 [ 2 39  0  3]
 [ 2 39  0  4]]
[[ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]]
